baseURL = "https://example.com"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "Hugo Serif Theme"
[[menu.footer]]
name = "Contatti"
url = "/contact/"
weight = 2
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Contatti"
url = "/contact/"
weight = 3
[[menu.main]]
name = "Chi Siamo"
url = "/about/"
weight = 1
[[menu.main]]
name = "Aree di Attività"
url = "/services/"
weight = 2
[module.hugoVersion]
extended = true
min = "0.55.0"
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.colors]
black = "#2f2f41"
grey = "#5C5A5A"
primary = "#191970"
white = "#ffffff"
white_offset = "#f6f7ff"
[params.fonts]
base = "Source Sans Pro"
google_fonts = "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap"
heading = "Playfair Display"
[params.footer]
copyright_text = "Free Hugo theme by <a class=\"zerostatic\" href=\"https://www.zerostatic.io\">www.zerostatic.io</a>"
[params.homepage]
show_contact_box = true
show_services_button = true
[params.logo]
alt = "STUDIO TAX PLANNING SACILE"
desktop = "images/logo.jpg"
desktop_height = "36px"
mobile = "images/logo.jpg"
mobile_height = "36px"
[params.seo]
meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"
meta_twitter_creator = "@zerostaticio"
meta_twitter_site = "@zerostaticio"
[params.team]
summary_large_truncate = 120
