baseURL = "https://example.com"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "Studio Tax Planning Sacile"
[[menu.footer]]
name = "Contatti"
url = "/contact/"
weight = 2
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Contatti"
url = "/contact/"
weight = 3
[[menu.main]]
name = "Chi Siamo"
url = "/about/"
weight = 1
[[menu.main]]
name = "Aree di Attività"
url = "/services/"
weight = 2
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.colors]
black = "#000080"
grey = "#5C5A5A"
primary = "#191970"
white = "#ffffff"
white_offset = "#f6f7ff"
[params.fonts]
base = "Source Sans Pro"
google_fonts = "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap"
heading = "Playfair Display"
[params.homepage]
show_contact_box = true
show_services_button = true
[params.logo]
alt = "STUDIO TAX PLANNING SACILE"
desktop = "images/Capture Black.jpg"
desktop_height = "55px"
mobile = "images/Capture Black.jpg"
mobile_height = "34px"
[params.seo]
meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"
meta_twitter_creator = "@TaxSacile"
meta_twitter_site = "@TaxSacile"
[params.team]
summary_large_truncate = 120
[params.footer]
copyright_text = 'Copyright © 2022 | Tutti i diritti riservati.'
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
map_marker = "static/images/map-marker.png"
